/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_itu_eyedroid_settings_Config */

#ifndef _Included_dk_itu_eyedroid_settings_Config
#define _Included_dk_itu_eyedroid_settings_Config
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getBeforeErode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getBeforeErode
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getBeforeDilate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getBeforeDilate
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getAfterErode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getAfterErode
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getAfterDilate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getAfterDilate
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getDiameterFactor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getDiameterFactor
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getConstantRoi_X
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getConstantRoi_1X
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getConstantRoi_Y
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getConstantRoi_1Y
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getConstantRoi_W
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getConstantRoi_1W
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getConstantRoi_H
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getConstantRoi_1H
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getPupilFoundRoi_W
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getPupilFoundRoi_1W
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getPupilFoundRoi_H
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getPupilFoundRoi_1H
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getThresholdLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getThresholdLimit
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getMinNeighborBlob
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getMinNeighborBlob
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getMinBlobSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getMinBlobSize
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getMaxBlobSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getMaxBlobSize
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getUpperThreshold
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getUpperThreshold
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getThresholdCenter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getThresholdCenter
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    getScaleFactor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dk_itu_eyedroid_settings_Config_getScaleFactor
(JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setBeforeErode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setBeforeErode
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setBeforeDilate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setBeforeDilate
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setAfterErode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setAfterErode
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setAfterDilate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setAfterDilate
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setDiameterFactor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setDiameterFactor
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setConstantRoi_X
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setConstantRoi_1X
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setConstantRoi_Y
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setConstantRoi_1Y
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setConstantRoi_W
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setConstantRoi_1W
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setConstantRoi_H
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setConstantRoi_1H
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setPupilFoundRoi_W
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setPupilFoundRoi_1W
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setPupilFoundRoi_H
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setPupilFoundRoi_1H
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setThresholdLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setThresholdLimit
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setMinNeighborBlob
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setMinNeighborBlob
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setMinBlobSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setMinBlobSize
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setMaxBlobSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setMaxBlobSize
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setUpperThreshold
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setUpperThreshold
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setThresholdCenter
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setThresholdCenter
(JNIEnv *, jclass, jint);

/*
 * Class:     dk_itu_eyedroid_settings_Config
 * Method:    setScaleFactor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_settings_Config_setScaleFactor
(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
