/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_itu_eyedroid_filters_EyeDetectionFilter */


#include <string>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/contrib/contrib.hpp>
#include <vector>

#ifndef _Included_dk_itu_eyedroid_filters_EyeDetectionFilter
#define _Included_dk_itu_eyedroid_filters_EyeDetectionFilter
#ifdef __cplusplus
extern "C" {
#endif

using namespace cv;
/*
 * Class:     dk_itu_eyedroid_filters_EyeDetectionFilter
 * Method:    createNativeObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dk_itu_eyedroid_filters_EyeDetectionFilter_createNativeObject
  (JNIEnv *, jclass);

/*
 * Class:     dk_itu_eyedroid_filters_EyeDetectionFilter
 * Method:    destroyNativeObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_EyeDetectionFilter_destroyNativeObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dk_itu_eyedroid_filters_EyeDetectionFilter
 * Method:    processNativeFrame
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_EyeDetectionFilter_processNativeFrame
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
