/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Eye.h"
#include "EyeDroid.h"
#include <string>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/contrib/contrib.hpp>
#include <vector>


/* Header for class dk_itu_eyedroid_filters_RGB2GRAYFilter */

#ifndef _Included_dk_itu_eyedroid_filters_RGB2GRAYFilter
#define _Included_dk_itu_eyedroid_filters_RGB2GRAYFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_itu_eyedroid_filters_RGB2GRAYFilter
 * Method:    rgb2gray
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_dk_itu_eyedroid_filters_RGB2GRAYFilter_rgb2gray
  (JNIEnv *, jclass, jlong, jlong);


/*
 * Class:     dk_itu_eyedroid_filters_BeforeErodeDilateFilter
 * Method:    beforeErodeDilate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_BeforeErodeDilateFilter_beforeErodeDilate
  (JNIEnv *, jclass, jlong);


/*
 * Class:     dk_itu_eyedroid_filters_ThresholdFilter
 * Method:    thresholdFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_ThresholdFilter_thresholdFrame
  (JNIEnv *, jclass, jlong);


/*
 * Class:     dk_itu_eyedroid_filters_AfterErodeDilateFilter
 * Method:    afterErodeDilate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_AfterErodeDilateFilter_afterErodeDilate
  (JNIEnv *, jclass, jlong);


/*
 * Class:     dk_itu_eyedroid_filters_BlobDetectionFilter
 * Method:    blobDetection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dk_itu_eyedroid_filters_BlobDetectionFilter_blobDetection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     dk_itu_eyedroid_filters_DetectAndDrawPupilFilter
 * Method:    detectPupilAndDraw
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_dk_itu_eyedroid_filters_DetectAndDrawPupilFilter_detectPupilAndDraw
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);



#ifdef __cplusplus
}
#endif
#endif
